### ISSUE TITLE
IPV6 issue

### ISSUE THREAD

**Issue by moh1122** [Microsoft/Cognitive-Face-iOS#19]
Hello
Camera feature doesn't work well on an IPV6 environment, can you help me please?
Thank you

**Comment by huxuan** [comment]
Hi @moh1122, I am not sure Camera feature has something to do with the network environment. Do you have any further specific information?

**Comment by moh1122** [comment]
What i mean exactly is that the app doesn't load on an IPV6 network

**Comment by huxuan** [comment]
AFAIK, cognitive services platform supports ipv6 (not Face API specifically), I do not think it is for Face iOS SDK sample only. Can you help me to confirm that? And also, I would suggest you can connect to Cognitive Services websites first as they are using the same endpoint.

**Comment by moh1122** [comment]
Hello
Thank you for your reply. 
Even on cognitive services websites there is no IPV6 connectivity. I think your domain and DNS servers should be IPV6 connected.

**Comment by huxuan** [comment]
Hi @moh1122, in this case, I do not think it is the right place to ask here. Guys who are in charge of cognitive services platform will not regularly check the issues here. I would suggest you to ask ipv6 support question on stackoverflow with `microsoft-cognitive`[1] as that is a formal support place now. Close as explained. 

[1] http://stackoverflow.com/questions/tagged/microsoft-cognitive
