### ISSUE TITLE
ListPersonsWithPersonGroupId not returning persisted Face Ids

### ISSUE THREAD

**Issue by NateRickard** [Microsoft/Cognitive-Face-iOS#21]
It appears that the API has changed since this SDK was last updated.  SDK seems to be expecting `faceIds` to be returned in the JSON:

https://github.com/Microsoft/Cognitive-Face-iOS/blob/master/Pod/Classes/MPOPerson.m#L39

Whereas the API docs state that `persistedFaceIds` will be returned:

https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395241

I can confirm via usage that the saved Face Ids are not being returned currently.

**Comment by huxuan** [comment]
Hi @NateRickard, thanks for the reporting.

Seems it is an iOS SDK error, we use `persistedFaceId(s)` as the face feature need to be stored persistently for further operation. This is different from the `faceId(s)` returned by `Detection` API as it will only cached for 24 hours.

Are you interested in fixing this issue? Feel free to reach me if you have any further problem.

**Comment by NateRickard** [comment]
Hi @huxuan - yes exactly, just a mismatch in the string keys being returned and what's expected.  I also logged #22 which is the same issue more or less.

I'm actually binding this SDK for Xamarin (to open source for others), so I'm not set up to build the Xcode project.  I can change the string (since it's a simple change) and send a PR, but I won't be able to build/test natively.  So let me know if you want me to do that or if you just want to change the strings quickly.

**Comment by huxuan** [comment]
Hi @NateRickard, OK, then I will handle this. Feel free to update if you find further tasty bugs. :-)
