### ISSUE TITLE
getPersonFaceWithPersonGroupId not returning persisted Face Id

### ISSUE THREAD

**Issue by NateRickard** [Microsoft/Cognitive-Face-iOS#22]
Related to #21 

MPOPersonFace expects `faceId` in the JSON:

https://github.com/Microsoft/Cognitive-Face-iOS/blob/master/Pod/Classes/MPOPersonFace.m#L38

API is now returning `persistedFaceId`:

```
{
    "persistedFaceId": "015839fb-fbd9-4f79-ace9-7675fc2f1dd9",
    "userData":"User-provided data attached to the person"
}
```

Reference: https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395240

**Comment by huxuan** [comment]
closed by pull request #23
