### ISSUE TITLE
Missing file - MPOFaceServiceClient.h when building

### ISSUE THREAD

**Issue by masonite** [Microsoft/Cognitive-Face-iOS#27]
Downloaded, installed pod, attempted to build, received the error message in the title.  

I notice the file was altered a few days ago, and wonder if some recent changes broke the project?

**Comment by huxuan** [comment]
Hummm, it is strange. I can not reproduce your error even with a clean installation. Previous changes should just be some minor changes with no structure change. Can you provide more specific information? I assume you are trying to run the sample, and please confirm you are using the latest version.

**Comment by masonite** [comment]
It was happening consistently to me on Sierra/Xcode 8.3.  Downloaded the GIT a few times, but couldn't get it to work.  What finally fixed it for me was to run: pod try ProjectOxfordFace.  After that, the project looked different, and I was able to successfully build it.

Sorry for how vague my information is.  I'll walk through it again tomorrow, and get you some better feedback.  For now, I'm going to close the issue as it's resolved on my end.
