### ISSUE TITLE
POFaceServiceClient error

### ISSUE THREAD

**Issue by samuelDeveloperiOS** [Microsoft/Cognitive-Face-iOS#36]
I built and ran the sample and change the subscription key and the End point with my credentials but when I tried to use the services every service return:

Domain=POFaceServiceClient error - http response is not success : { "statusCode": 404, "message": "Resource not found" }

I have a cognitive account and a free trial both with different end points and keys, I tried with both but I have gotten the same error.

Add these links with the images with the accounts, keys and end points, the debug screenshot and MPOAppDelegate.h
  
[https://drive.google.com/open?id=0B0Q7Z65PAH9ocVBmcVlKOERFYmc](url)
[https://drive.google.com/open?id=0B0Q7Z65PAH9oanpGeGpWeGM5Rnc](url)
[https://drive.google.com/open?id=0B0Q7Z65PAH9oODV5aGx4S0pyUFk](url)
[https://drive.google.com/open?id=0B0Q7Z65PAH9oNW1FckFpVGE0dDA](url)

I hope you can help me with this issues. (y)

**Comment by cthrash** [comment]
Does `ProjectOxfordFaceEndpoint` contain a space between `.com/` and `face/v1.0`?  It looks like this might be the case based on the last screenshot.

**Comment by samuelDeveloperiOS** [comment]
No, that is not the problem, this is the end point https://westcentralus.api.cognitive.microsoft.com/face/v1.0

**Comment by huxuan** [comment]
Can you provide any other changes you have made?

**Comment by samuelDeveloperiOS** [comment]
I only cloned this repository and assigned ProjectOxfordFaceSubscriptionKey and ProjectOxfordFaceEndpoint, then I tried to use the app but the services didn't work.

**Comment by huxuan** [comment]
There need to have an hard-coding slash `/` at the end of endpoint. Would you please to have a try on it?

**Comment by samuelDeveloperiOS** [comment]
Thank you so much. Now it is working. (y)

**Comment by huxuan** [comment]
Yep, I have to admit it is a imperfect hard-coding pattern, will consider to improve it in the feture.

Close as  problem solved.
