### ISSUE TITLE
How to Identify a person from his/her Picture that he/she has first logged in or not ?

### ISSUE THREAD

**Issue by TimeToCodeIos** [Microsoft/Cognitive-Face-iOS#38]
Hi,
     Is it possible , that i have array of already logged in FaceIds and now when i am taking selfie of user and from his/her picture can i check whether he/she has already logged in (before from Only his/her picture )?

**Comment by huxuan** [comment]
A short answer should be using `Person Group` [1] and `Verify` [2]. For further questions, please ask them at StackOverFlow [3] as that is the official support forum and there will be more detailed response there.

Github is mostly for technical issues (e.g. bugs of iOS SDK) rather support. So close this issue.

* [1] https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395244
* [2] https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395239
* [3] https://stackoverflow.com/questions/tagged/microsoft-cognitive
