### ISSUE TITLE
POFaceServiceClient error 

### ISSUE THREAD

**Issue by tianxuefeng** [Microsoft/Cognitive-Face-iOS#39]
Error Domain=POFaceServiceClient error - http response is not success : { "statusCode": 404, "message": "Resource not found" } Code=404 "(null)"

I have set correct endpoint and subscription key, however, keeping get above error.
static NSString *const ProjectOxfordFaceSubscriptionKey = @"#################";
static NSString *const ProjectOxfordFaceEndpoint = @"https://southeastasia.api.cognitive.microsoft.com/face/v1.0";

I also tried Cognitive-Face-Android, it is very easy to use and no error.

**Comment by overbrimming** [comment]
Tian- I've editing your comment to remove what looks like it may have been your API key. Please regenerate your key if this comment did leak it! In the Azure portal, open your Face API Subscription. Under "Resource Management" select "Keys" and then "Regenerate Key" (1 or 2 depending on which you published.

**Comment by huxuan** [comment]
You may need to add a trailing slash at the end of endpoint settings.

**Comment by tianxuefeng** [comment]
Thanks for your big help!

It is works!



Thanks!

Best Regards,
Xuefeng

2017-09-15 6:38 GMT+08:00 Xuan Hu (Sean) <notifications@github.com>:

**Comment by huxuan** [comment]
Close as the problem solved.
