### ISSUE TITLE
Coach on swift 4.0 version 

### ISSUE THREAD

**Issue by chandanmishra1995** [Microsoft/Cognitive-Face-iOS#40]
Hello team,
I have tried this SDK on swift 4.0 version and import  MPOFaceSDK.h and #import <ProjectOxfordFace/MPOFaceSDK.h> in bridging header 
after integration and apply the face detect code it get crash in completion block, says  Thread 1: EXC_BAD_ACCESS (code=1, address=0x10) ,
 please provide any SDK on swift version.
Or give any solution to implement this SDK on swift.

![screen shot 2017-11-01 at 7 53 13 pm](https://user-images.githubusercontent.com/33287952/32279308-64a29d2e-bf3e-11e7-9c1f-6258490b4f1a.png)

**Comment by chandanmishra1995** [comment]
Now it is working, my pod is not working well so that i got all the files in internal structure
Thanks for giving me your time.

**Comment by huxuan** [comment]
Close as problem resolved.
