### ISSUE TITLE
Example Code Not Working on iOS 11.1.2

### ISSUE THREAD

**Issue by leonsg** [Microsoft/Cognitive-Face-iOS#41]
**When I select an image for processing I get the following error:**
ProjectOxfordFace_Example[17589:7783160] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
**When I call detect I get the following error:**
ProjectOxfordFace_Example[17620:7786392] [BoringSSL] Function nw_protocol_boringssl_get_output_frames: line 1183 get output frames failed, state 8196

Could some one help look into this please?

**Comment by huxuan** [comment]
Hi @leonsg, is there any useful information to share? Actually I personally have not verify the iOS 11 compatibility.
