### ISSUE TITLE
"Resource not found" message.

### ISSUE THREAD

**Issue by cnavarro2014** [Microsoft/Cognitive-Face-iOS#42]
Hi guys,

I've been trying to implement the service for a login view, I started the Face API service on my Azure account and already got the subscription keys, but so far I haven't been able to get this to work!
As a response, i get a "Resource not found" statusCode = 404.
I am in Mexico (not in the US), I'm afraid this could be the reason why this is not workin, any clue on this please?
Thank you in advance...

**Comment by huxuan** [comment]
Will this (#37) be helpful?

**Comment by cnavarro2014** [comment]
Awesome @huxuan !  I can't believe it was the closing slash! been trying to find the solution for 3 days =). Thanks again...

**Comment by ArchanaSan** [comment]
Hello cnavarro2014, can u pls share the code? I'm also facing same issue.
