### ISSUE TITLE
getting linking Error with Xcode 9.2

### ISSUE THREAD

**Issue by NikhilPrajapat1994** [Microsoft/Cognitive-Face-iOS#44]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PersistedFace", referenced from:
      objc-class-ref in MPOSimilarFaceViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by StephGuyzmo** [comment]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PersistedFace", referenced from:
      objc-class-ref in MPOSimilarFaceViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vengalraopnws** [comment]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_PersistedFace", referenced from:
      objc-class-ref in MPOSimilarFaceViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vengalraopnws** [comment]
Undefined symbols for architecture arm64: "_OBJC_CLASS_$_PersistedFace", referenced from: objc-class-ref in MPOSimilarFaceViewController.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1

**Comment by ribbon-xx** [comment]
#metoo and they dropped their project

**Comment by huxuan** [comment]
Hi everyone, thanks for your reporting and sorry for the late reply.
The corresponding issue should have been fixed by pull request #45.
Specially thanks to @llkpersonal for the contribution.
I also updated the version to 1.4.1 and it is already updated in cocoapods.
Please feel free to try the new version and let me know if there is any concern.

**Comment by huxuan** [comment]
Close as problem resolved. Please feel free to reopen it if there is any further related questions.
