### ISSUE TITLE
unknow error: please check response

### ISSUE THREAD

**Issue by ChinmayNayak007** [Microsoft/Cognitive-Face-iOS#47]
i am facing unknown error: please check response when called microsoft face api

**Comment by huxuan** [comment]
Hi @ChinmayNayak007, thanks for using Face API and the iOS SDK, could you provide more information about how you encounter that error?

**Comment by ChinmayNayak007** [comment]
i am implementing project-oxford in ios.
when i click take picture button which will call face api, that time i am facing this error.

**Comment by huxuan** [comment]
If you are using the SDK sample, please double confirm you are using the right endpoint and corresponding subscription id.

**Comment by huxuan** [comment]
Close since there is no further response. Please feel free to reopen or create a new one if there is any other questions.
