### ISSUE TITLE
Service error : "RateLimitExceeded"

### ISSUE THREAD

**Issue by wirakoon78** [Microsoft/Cognitive-Face-iOS#9]
I use Find Similar api : https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395237

to find similar faces. 
I uploaded 148 photos but always get this error from the server .

{ "error":{ "statusCode": 429, "message": "Rate limit is exceeded. Try again later." } }"

I have no idea what the problem is . Could you please let me know what the issue is . 
Thanks in advance.

**Comment by huxuan** [comment]
Free subscriptions have a calling frequency limitation, which is `30,000 transactions per month, 20 per minute`. You should be able to see your quota via the link here [1].

[1] https://www.microsoft.com/cognitive-services/en-US/subscriptions

**Comment by huxuan** [comment]
Close as no further update from reporter.
